apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    application: coolstore
    component: cart
  name: cart
spec:
  replicas: 1
  selector:
    deploymentconfig: cart
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        application: coolstore
        component: cart
        deploymentconfig: cart
      name: cart
    spec:
      containers:
      - env:
        - name: CATALOG_ENDPOINT
          value: http://catalog:8080
        - name: APPLICATION_MODE
          value: prod
        image: {{REGISTRY}}/coolstore-dev/cart:@APP_VERSION@
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: cart
        ports:
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 75
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - cart
      from:
        kind: ImageStreamTag
        name: cart:@APP_VERSION@
        namespace: coolstore-dev
    type: ImageChange
  - type: ConfigChange
